### ISSUE TITLE
Text strings from DataTables should be displayed in the chosen language as well (public front web app)

### ISSUE THREAD

**Issue by heidivanparys** [ec-jrc/re3gistry#113] opened 2021-12-06 19:31 UTC
See screenshot below: the values displayed by DataTables are shown in English, whereas the chosen language in this case was Danish.

![image](https://user-images.githubusercontent.com/11427611/144908513-c2be2461-25d7-431e-b7ae-6f2660289ed4.png)

The text strings from DataTables should be localized as well. Fx for Danish that would be:

```javascript
$('.table').DataTable( {
		"language": {
			"url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/da.json"
		},
		"...": "..."
	} );
```

A quick search shows that changes probably would be needed around here:

https://github.com/ec-jrc/re3gistry/blob/7f929931c4976e90e98037fe1e563cb66a8129cb/dist/webapp/public_html/js/app_core.js#L127-L139

**Comment by arantzaetxebarria** [comment] 2023-12-11 14:10
The issue is closed as it is related to https://github.com/ec-jrc/re3gistry/issues/212

**Closed by arantzaetxebarria** 2023-12-11 14:10 UTC
Labels: Type: Enhancement
